[features]
seeds = false
skip-lint = false
[programs.localnet]
msgs = "7RJGUEhX5k1CfMnC32KAvLUR491idVkD6KHtrkAT4vjX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = ".BobKX3z3oHUBQ3X4eZRGHwfqm18YfhGJuijiUtC2Gy2m.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
